version: '3.8'
services:
  db:
    image: mysql
    container_name: library-simplified
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - library-simplified:/var/lib/library-simplified

volumes:
  library-simplified:
